### PR TITLE
Closed tasks should be displayed by default in boards and dashboard

### PR DESCRIPTION
**Pull request by vincowl**
Cf Issue #4100 
[x] I read the [contributor guidelines](https://docs.kanboard.org/en/latest/developer_guide/contributing.html#i-want-to-contribute-to-the-code)

### CODE REVIEW

**Comment by vincowl** [comment]
Should update `UserSessionTest::testFilters` in `kanboard/kanboard/tests/units/Core/User/UserSessionTest.php:86`
```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'status:open'
+'status:all'
```
Waiting for your point of view on this PR

**Comment by rafacamargo123** [comment]
Sorry to ask, but how many closed tasks do you have?
My project has over 2000 closed tasks ans this behaviour would break usability (browser takes several seconds to render all tasks)

**Comment by rafacamargo123** [comment]
Sorry to ask, but how many tasks does your project has?
We have a project with over 2000 tasks done, this behaviour would break kanboards usability, because browsers take many seconds to render all the tasks... I think a better solution would be to make the default filter configurable, at least globally, by instalation, maybe (config.php).

**Comment by vincowl** [comment]
I don't have so much tasks indeed. For such large projects, I use Gitlab.
Just for my personal info, do the use of swimlanes reduces tasks' rendering
?

Finally, it seems that everyone agrees to say that this optional default
filter may be a good option. Would it be better to set it up at a global
level or at the project's one ?

Le mar. 11 déc. 2018 à 20:46, rafacamargo123 <notifications@github.com> a
écrit :

**Comment by rafacamargo123** [comment]
I have a swimlane with 127 tasks total and another with over 2500. Keeping only the smaller swimlane opened does not reduce tasks rendering time.
I guess it is easier to implement at global level (can be a simple new constant on config.php), if it suits your needs, but I don't know what most users expect.

**Comment by vincowl** [comment]
Ok. Thanks for this info. I didn't have a look at the page's structure.

Implementation at global level would be perfect to me since all my projects
in this Kanboard instance follow the same guidelines. But that would be a
pain if projects are notre consistent in a single Kanboard instance. If
this global variable is not set, it should of course behave as is.

To have an idea of my perds, check the related PR (note the point that
closed tasks should then be added to open ones in dashboard view). I just
found out that I forgot to modify the tasks count in a project activity.

Le 11 déc. 2018 21:16, "rafacamargo123" <notifications@github.com> a écrit :

I have a swimlane with 127 tasks total and another with over 2500. Keeping
only the smaller swimlane opened does not reduce tasks rendering time.
I guess it is easier to implement at global level (can be a simple new
constant on config.php), if it suits your needs, but I don't know what most
users expect.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kanboard/kanboard/pull/4101#issuecomment-446346428>,
or mute
the thread

**Comment by vincowl** [comment]
@fguillot I have already done it. But as said in #4100, this project organization also implies to modify the overview dashboard to also count closed tasks in columns, and it means to change the default behavior, not just a way to change the filters. That's why @rafacamargo123's proposal seems ways better to me than simply just add a custom filter.
If default or unset value implies to keep the actual behavior then it won't have any impact on people

**Comment by creecros** [comment]
@vincowl 

You could use use the configModel and add a default filter option in the application settings. In template/config/application.php add:
```php
    <fieldset>
        <?= $this->form->label(t('Default Filter'), 'application_stylesheet') ?>
        <?= $this->form->textarea('application_default_filter', $values, $errors) ?>
    </fieldset>
```
in UserSession.php, change the return in getFilters to:
```php
            return session_get('user')['filter'] ?: $this->configModel->get('application_default_filter', 'status:open');	
```

etc...

could easily be a extension without the need for a PR as well.

**Comment by vincowl** [comment]
@creecros 
Thanks a lot for these infos. I had no time before, but I will have a look at it in the next days. Indeed the solution is to design a plugin. I am lacking infos on how to do it and more precisely on what can be made or not. As I tried to explain, the need is not only limited to the filter aspect but also to the analysis part (I mean include closed tasks to statistics given on the analysis project's mode, but also on dashboards and overviews). How far can a plugin modify the actual behavior ? If this can be done, I will have a look on how to design a plugin.  Thanks !!

**Comment by creecros** [comment]
@vincowl From a plug in perspective, I don't think I've yet to not figure out how to do something...given enough time. I am not working on anything new atm, just maintaining my current repos, so happy to help if needed.

**Comment by fguillot** [comment]
Closing this PR. Sorry, I don't want to change the default behaviour. You can continue the discussion on the forum: https://kanboard.discourse.group/.

**Pull request closed without merging**
