### PR TITLE
Fixes issue #4359. Updating the regex for matching attachment external links

### PR DESCRIPTION
**Pull request by SladeP**
Fix for #4359 . 

[Closed pull request](https://github.com/kanboard/kanboard/pull/4382)

Updated the regular expression so that https://github.io will count as a web link and https://github.io/test.jpeg will count as an attachment.

See #4359 for more comments on this solution.

### CODE REVIEW

**Comment by fguillot** [comment]
The unit tests are failing with `preg_match(): Unknown modifier '.'` https://travis-ci.org/kanboard/kanboard/jobs/643160111?utm_medium=notification&utm_source=github_status

**Comment by SladeP** [comment]
And I'm unable to even get unit tests to run on my local with Docker to replicate. Trying to figure out what the issue is, sorry about the delay.

**Comment by SladeP** [comment]
Got the unit tests to work locally and adjusted the regex so that it should pass unit tests. Fingers crossed. Sorry it's in 2 commits, I don't know another way to do it if I don't just delete the branch and create yet another PR.

**Comment by SladeP** [comment]
Actually, even if it passes, don't merge it. I'm going to add unit test cases for urls like github.io and github.io/test.html

**Pull request closed without merging**
