### PR TITLE
Add Better SVG Version of Kanboard Icon

### PR DESCRIPTION
**Pull request by aljawaid**
This is a better copy of the `png` versions

### CODE REVIEW

**Comment by aljawaid** [comment]
> Where is this SVG file coming from? How was it generated? What is the difference between this one: https://github.com/kanboard/kanboard/blob/main/assets/img/icon.svg

I converted it from the `png` version. If you compare both svg files, my version is identical and based on the png version.

**Comment by aljawaid** [comment]
> Where is this SVG file coming from? 

I made it for my plugin to create this:
image

**Comment by aljawaid** [comment]
> How was it generated? 
I used _Convertico_

**Comment by aljawaid** [comment]
@fguillot I will close this PR.  It seems obvious that you don't want Kanboard to improve or develop regardless of your thinking.  Other developers are trying their best to keep Kanboard going and updated, but regardless of their efforts you are not encouraging much.  In 2023, Kanboard only seems to be alive because of the plugins and nothing else.

**Comment by nekohayo** [comment]
I see here that Frédéric was asking objective technical questions on the origins and the need for this change, as your original statement didn't make that clear. I would have asked the same questions (why would you generate new SVGs from PNGs, instead of reusing the existing SVG, or derivating from the SVG, etc.).

Unlike what you think, from the outset this was/is not a straightforward, "obvious" change that must be made, from the point of view of any onlooker. Your argument as to why this is needed is not clear to me either. "Better icon" doesn't say/mean anything. Comparing [your SVG](https://github.com/aljawaid/kanboard/blob/main/assets/img/kanboard-icon.svg) to [the original SVG](https://github.com/aljawaid/kanboard/blob/main/assets/img/icon.svg) I initially failed to see the reason for your change; as I result, I independently (as a non-developer, but as an independent brand designer) came to the same intuitive "....Huh?!" puzzlement as Frédéric.

Yet when Frédéric politely asked for such clarifications, and didn't respond "fast enough" to your latest response (I'm pretty sure he has other things to do in his life and can't guarantee same-week turnaround here), you just went from 0 to 100 immediately with a flippant victim attitude (and generalizations) and decided to take your ball home when reality doesn't match your worldview? And then you try to [stir up drama in a forum thread](https://kanboard.discourse.group/t/why-is-kanboard-core-so-difficult-to-collaborate-on/2612), repeatedly making it sound like a this is a deep injustice, obstruction, and that Frédéric has inscrutable intentions and is being difficult? Dude, get a grip.

Looking at the technical aspect of this change, objectively, and re-reading your comments above a couple more times, I see that what you're trying to accomplish is provide a vector version _where the letters are vector shapes_ instead of actual text elements. Well,
1. This could have been explained clearly from the start;
2. You could do this from the SVG icon by opening it with Inkscape on Linux, where it was certainly made (where "Sans" is going to render fine as a font) and then making your outlined SVG variant from that SVG instead of reverse-engineering PNGs, which would be a cleaner approach.

**Comment by aljawaid** [comment]
> I see here that Frédéric was asking objective technical questions on the origins and the need for this change, as your original statement didn't make that clear. I would have asked the same questions (why would you generate new SVGs from PNGs, instead of reusing the existing SVG, or derivating from the SVG, etc.).
> 
> Unlike what you think, from the outset this was/is not a straightforward, "obvious" change that must be made, from the point of view of any onlooker. Your argument as to why this is needed is not clear to me either. "Better icon" doesn't say/mean anything. Comparing [your SVG](https://github.com/aljawaid/kanboard/blob/main/assets/img/kanboard-icon.svg) to [the original SVG](https://github.com/aljawaid/kanboard/blob/main/assets/img/icon.svg) I initially failed to see the reason for your change; as I result, I independently (as a non-developer, but as an independent brand designer) came to the same intuitive "....Huh?!" puzzlement as Frédéric.
> 
> Yet when Frédéric politely asked for such clarifications, and didn't respond "fast enough" to your latest response (I'm pretty sure he has other things to do in his life and can't guarantee same-week turnaround here), you just went from 0 to 100 immediately with a flippant victim attitude (and generalizations) and decided to take your ball home when reality doesn't match your worldview? And then you try to [stir up drama in a forum thread](https://kanboard.discourse.group/t/why-is-kanboard-core-so-difficult-to-collaborate-on/2612), repeatedly making it sound like a this is a deep injustice, obstruction, and that Frédéric has inscrutable intentions and is being difficult? Dude, get a grip.
> 
> Looking at the technical aspect of this change, objectively, and re-reading your comments above a couple more times, I see that what you're trying to accomplish is provide a vector version _where the letters are vector shapes_ instead of actual text elements. Well,
> 
>     1. This could have been explained clearly from the start;
> 
>     2. You could do this from the SVG icon by opening it with Inkscape on Linux, where it was certainly made (where "Sans" is going to render fine as a font) and then making your outlined SVG variant from that SVG instead of reverse-engineering PNGs, which would be a cleaner approach.

WOW, dude YOU need to get a grip... Try to develop a plugin and see the frustration in trying to get Kanboard updated. I didn't try to create a stir in a forum thread, I was sharing my frustration with others... if you wanted, you could have replied there but NO you wanted to isolate yourself here so you got the upper hand and try to humiliate me in a different channel.  You obviously read the mixed responses there!

Anyway, get a life... I proposed a change, it didn't happen, I closed the PR because I didnt want it in my open issues list non-stop... there are open issues from 2019 if you actually bothered to notice them.  

Im done wasting my time on this PR and I now regret ever suggesting a change and I dont welcome your response either.  Oh and if you knew so much about branding, you would have spotted the obvious mistake.

**Comment by aljawaid** [comment]
> I see here that Frédéric was asking objective technical questions on the origins and the need for this change, as your original statement didn't make that clear. I would have asked the same questions (why would you generate new SVGs from PNGs, instead of reusing the existing SVG, or derivating from the SVG, etc.).
> 
> Unlike what you think, from the outset this was/is not a straightforward, "obvious" change that must be made, from the point of view of any onlooker. Your argument as to why this is needed is not clear to me either. "Better icon" doesn't say/mean anything. Comparing [your SVG](https://github.com/aljawaid/kanboard/blob/main/assets/img/kanboard-icon.svg) to [the original SVG](https://github.com/aljawaid/kanboard/blob/main/assets/img/icon.svg) I initially failed to see the reason for your change; as I result, I independently (as a non-developer, but as an independent brand designer) came to the same intuitive "....Huh?!" puzzlement as Frédéric.
> 
> Yet when Frédéric politely asked for such clarifications, and didn't respond "fast enough" to your latest response (I'm pretty sure he has other things to do in his life and can't guarantee same-week turnaround here), you just went from 0 to 100 immediately with a flippant victim attitude (and generalizations) and decided to take your ball home when reality doesn't match your worldview? And then you try to [stir up drama in a forum thread](https://kanboard.discourse.group/t/why-is-kanboard-core-so-difficult-to-collaborate-on/2612), repeatedly making it sound like a this is a deep injustice, obstruction, and that Frédéric has inscrutable intentions and is being difficult? Dude, get a grip.
> 
> Looking at the technical aspect of this change, objectively, and re-reading your comments above a couple more times, I see that what you're trying to accomplish is provide a vector version _where the letters are vector shapes_ instead of actual text elements. Well,
> 
>     1. This could have been explained clearly from the start;
> 
>     2. You could do this from the SVG icon by opening it with Inkscape on Linux, where it was certainly made (where "Sans" is going to render fine as a font) and then making your outlined SVG variant from that SVG instead of reverse-engineering PNGs, which would be a cleaner approach.

You're actually not worth a reply at all!

**Pull request closed without merging**
