### PR TITLE
update german translation

### PR DESCRIPTION
**Pull request by OHDMax**
I removed some inconsistencies like using the word "User" instead of "Benutzer" in the german translation

### CODE REVIEW

**Comment by OHDMax** [comment]
I found another spelling error, which is not part of this PR but rather annoying since the text is displayed every time a task is created. It's in [line 1209](https://github.com/kanboard/kanboard/blob/master/app/Locale/de_DE/translations.php#L1209). Where it says "iHre" it should be "Ihre". Shall I create another PR for this typo?

**Comment by fguillot** [comment]
I would prefer someone who speaks German to fix typos :)

**Comment by fguillot** [comment]
So yes, you could send another PR.

**Comment by OHDMax** [comment]
I do, it's my mother tongue ;)

**Pull request merged**
