### PR TITLE
Add new filters based on task links

### PR DESCRIPTION
**Pull request by arnaud-jacquemin**
- `link:none` => show only tasks that are not linked to other tasks
- `link:toplevel` => show only tasks that are not a child of other tasks

### CODE REVIEW

**Comment by fguillot** [comment]
Are you willing to add some unit tests?

**Comment by rafacamargo123** [comment]
@arnaud-jacquemin, will you add the unit tests? If you wish I can do it. To do so and keep your commit and a single PR, I can fork your fork and create a pull request with the modifications in your repo.

**Comment by arnaud-jacquemin** [comment]
Hi Frédéric and Rafael,
I'm a bit busy at the moment, sorry... I won't be able to write unit tests this week. Maybe this weekend but I'm not sure. 
@rafacamargo123 If you're willing to do it, no problem!

**Comment by fguillot** [comment]
Conflicts with PR #4264. Please update your PR.

**Pull request closed without merging**
