### PR TITLE
Russian documentation added

### PR DESCRIPTION
**Pull request by hairetdin**
**Added Russian documentation.**
- I created a Russian documentation in the draft (need spell check). To translate documentation to Russian used http://www.sphinx-doc.org. Sphinx is useful for creating translations, but I did not understand how create Russian markdown translations. So, I converted Markdown documentation to reStructuredText using pandoc, translated po files, then Russian documentation made in html, and then transformed html into a markdown using pandoc. 
- [Project Russian translation Kanboard](https://github.com/hairetdin/kanboard-doc-ru).
- I don't understand how to connect documentation to the application, therefore could not test.
- If necessary, I can do PDF, EPUB Russian documentation in Sphinx.

### CODE REVIEW

**Comment by fguillot** [comment]
To create a new documentation translation: 
- Create a new folder "doc/ru_RU"
- Copy the English Markdown files to the new folder with the same filename
- Translate the file contents in Russian
- You can view the results from the application itself:
   - Set the application language to Russian
   - Open the dropdown menu on the top right (username menu) > choose "Documentation"
   - Or use any desktop Markdown viewer or even Github

Is there a way to include only the Markdown files from the work you have already done? 300 files is a lot, this is probably better to keep that on a separate repository.

**Comment by hairetdin** [comment]
- Removed src English files folder.
- Tested Russian documentation in application.
- Russian Markdown documentation available in Russian translation repository - https://github.com/hairetdin/kanboard-doc-ru/tree/master/build/markdown .
- Also, Russian html documentation with search available on http://kanboard.ru/doc/

**Comment by hairetdin** [comment]
Russian documentation in doc/ru_RU contain only markdown files

**Comment by fguillot** [comment]
I was about to merge but why there are extra blank lines and spaces everywhere?

The page formatting is broken for most of the pages:

ru

**Comment by hairetdin** [comment]
It happened after conversion : markdown - > reStructuredText - > translate to Russian in Sphinx po files - > HTML - > markdown. I did not use the editor when doing translation. I just translated .po files in  [Gtranslator](https://en.wikipedia.org/wiki/Gtranslator).
I will bring in the order of Russian documentation in markdown format, as will the time. 
While the fixed table.

**Comment by hairetdin** [comment]
Formatting corrected

**Pull request merged**
