### PR TITLE
Per-project and per-swimlane task limits

### PR DESCRIPTION
**Pull request by andrenth**
This PR allows projects and swimlanes to be configured with task limits that apply to their whole scope (i.e. all active tasks in a project or swimlane, respectively), as opposed to the usual per-column task limits.

### CODE REVIEW

**Comment by andrenth** [comment]
Sorry for that. I've modified the tests to catch this, and fixed the query to work on Postgres.

**Comment by fguillot** [comment]
I found another SQL issue with Postgres. When creating a new project, this error is raised: 

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""
```

The corresponding SQL is `INSERT INTO "projects" ("name", "is_private", "identifier", "per_swimlane_task_limits", "task_limit", "token", "last_modified", "owner_id") VALUES (:name, :is_private, :identifier, :per_swimlane_task_limits, :task_limit, :token, :last_modified, :owner_id)`

**Comment by andrenth** [comment]
The latest commit adds `task_limit` to the list of numeric fields, and adds a test to catch this error.

**Comment by fguillot** [comment]
Looks like there is a small glitch in the ui when creating a project with take limit:

image

The 0 is missing.

**Comment by andrenth** [comment]
I hadn't realized the open task count was returned as NULL when the project has no tasks. I've changed the template to use `intval` on it.

**Pull request merged**
