### PR TITLE
Fix board column header alignment

### PR DESCRIPTION
**Pull request by Jieiku**
This Change fixes the vertical alignment of column headers, the end result is this:

instead of this:

It is a very subtle change, look a the vertical alignment of the text next to the "+" button for adding tasks.

Github does not show a very good diff for the single line .css file, the only change was the css I added for the new div class:

This area of css:

`.board-column-collapsed{display:none}`

became this:

`.board-column-collapsed{display:none}.board-column-expanded-header{display:flex;align-items:center}`

Also this is the minified css file. It was the only file I needed to edit to put this change into affect, I am not sure if this new entry needs to be added to a non minified css someplace, for future maintainability....

I searched the other css files on my system for:
`.board-column-collapsed`

I could not find that entry anywhere else, only in the minified css file.... So my assumption was the NON minified css files are not really being maintained or have missing entries that are present in the minified css.

Do you follow the guidelines?

- [x] I have tested my changes
- [x] There is no breaking change
- [x] There is no regression
- [x] I follow existing [coding style](https://docs.kanboard.org/en/latest/developer_guide/coding_standards.html)

### CODE REVIEW

**Review by fguillot — CHANGES_REQUESTED** [review]
You have modified the minified file instead of the source file.

See: https://docs.kanboard.org/en/latest/developer_guide/assets.html

**Comment by Jieiku** [comment]
Thanks i am checking out your link now. Will fix shortly.

**Comment by Jieiku** [comment]
There I modified the board.css in the correct place, just below

**Review by fguillot — APPROVED** [review]

**Comment by almmos** [comment]
Hi,
I think this commit and subsequent merge operation has introduced kind of a problem related to 
'**Hide this column**' operation on a column in main Board view.
Checking the [commit found here](https://github.com/kanboard/kanboard/commit/e745f8a23504368d456a879cc67e9bf2279e72ae) I can quickly see that 
for `app/Template/board/table_column.php` and `app/Template/board/table_column_first.php` files, 
CSS class `board-column-expanded` is **replaced** with a brand new `board-column-expanded-header` CSS class.

The real problem became apparent when we take a look at [Kanboard.BoardColumnView.prototype.hideColumn method](https://github.com/kanboard/kanboard/blob/0216a3136b386ba05e2ce8339942f8490aca0f6b/assets/js/src/BoardColumnView.js#L44-L64) 
``` php
Kanboard.BoardColumnView.prototype.hideColumn = function(columnId) {
    $(".board-column-" + columnId + " .board-column-expanded").hide();
    $(".board-column-" + columnId + " .board-column-collapsed").show();
    $(".board-column-header-" + columnId + " .board-column-expanded").hide();
    $(".board-column-header-" + columnId + " .board-column-collapsed").show();

    $(".board-column-header-" + columnId).each(function() {
        $(this).removeClass("board-column-compact");
        $(this).addClass("board-column-header-collapsed");
    });

    $(".board-column-" + columnId).each(function() {
        $(this).addClass("board-column-task-collapsed");
    });

    $(".board-column-" + columnId + " .board-rotation").each(function() {
        $(this).css("width", $(".board-column-" + columnId + "").height());
    });

    localStorage.setItem("hidden_column_" + columnId, 1);
};
```
and [Kanboard.BoardColumnView.prototype.showColumn method](https://github.com/kanboard/kanboard/blob/0216a3136b386ba05e2ce8339942f8490aca0f6b/assets/js/src/BoardColumnView.js#L66-L80) 
```
Kanboard.BoardColumnView.prototype.showColumn = function(columnId) {
    $(".board-column-" + columnId + " .board-column-expanded").show();
    $(".board-column-" + columnId + " .board-column-collapsed").hide();
    $(".board-column-header-" + columnId + " .board-column-expanded").show();
    $(".board-column-header-" + columnId + " .board-column-collapsed").hide();

    $(".board-column-header-" + columnId).removeClass("board-column-header-collapsed");
    $(".board-column-" + columnId).removeClass("board-column-task-collapsed");

    if (localStorage.getItem("horizontal_scroll") == 0) {
        $(".board-column-header-" + columnId).addClass("board-column-compact");
    }

    localStorage.removeItem("hidden_column_" + columnId);
};
```
 in '_[assets/js/src/BoardColumnView.js](https://github.com/kanboard/kanboard/blob/main/assets/js/src/BoardColumnView.js)_' file.
 
 On lines no: **45**, **47** and respectively **67** and **69**, as are they numbered in the already linked file, 
 there are `jquery` operations executed based on _`board-column-expanded`_ CSS class selector.
 I am new related to all **Kanboard** code and I don't know the full implications related.
 
 **My quick FIX** was to '**add**'  - _not to replace back_ - the old CSS class _`board-column-expanded`_ 
 needed by the `javascript` methods already mentioned.
 
**In** [file app/Template/board/table_column.php](https://github.com/kanboard/kanboard/blob/main/app/Template/board/table_column.php) I have changed line no 17 from
 `<div class="board-column-expanded-header">` to `<div class="board-column-expanded board-column-expanded-header">`.

**Similarly in** [file app/Template/board/table_column_first.php](https://github.com/kanboard/kanboard/blob/main/app/Template/board/table_column_first.php) I have changed line no 10 from
`<div class="board-column-expanded-header">` to `<div class="board-column-expanded board-column-expanded-header">`.

Hope this is helpful for somebody, thanks for all the hard work. VV

**Pull request merged**
