### PR TITLE
Improve swimlane columns headers

### PR DESCRIPTION
**Pull request by manne65-hd**
Do you follow the guidelines?

- [x] I have tested my changes
- [ ] There is no breaking change
- [x] There is no regression
- [x] I follow existing [coding style](https://docs.kanboard.org/en/latest/developer_guide/coding_standards.html)

I have had another idea [to improve my latest commit](https://github.com/kanboard/kanboard/pull/4791) even further ...

Now rendering an empty columns-header first, thus enabling swimlane-headers to appear above the comlum-headers, which really looks much better IMHO

Maybe my CSS-addons could be improved, but I am not the best at CSS, so am open to comments ;-)

### CODE REVIEW

**Comment by manne65-hd** [comment]
Oooops :-O 

Was so happy, it (seemed) to work ... that I didn't realize, that the column is too wide when collapsed 

**Needs further improvement ...  not ready to be pulled into the codebase !!**

Will do further commits to this PR as soon as I (hopefully) find the missing parts (seems to be I also need to adjust some of the JS-code)

**Comment by manne65-hd** [comment]
OK ... I think I finally figured it out :-)
Have tested again _(including viewing and collapsing colums with my mobile phone)_ and am confident, that it is working now.

Here are some screenshots
------------------------------
All SwimlanesOpen / All ColumnsOpen
01-AllSwimlanesOpen-AllColumnsOpen

All SwimlanesOpen / 1 ColumnCollapsed
02-AllSwimlanesOpen-1ColumnCollapsed

All SwimlanesOpen / 1 ColumnCollapsed (CompactView)
03-AllSwimlanesOpen-1ColumnCollapsed-CompactView

2 SwimlanesCollapsed / 1 ColumnCollapsed
04-2SwimlanesCollapsed-1ColumnCollapsed

2 SwimlanesCollapsed / 1 ColumnCollapsed (CompactView)
04-2SwimlanesCollapsed-1ColumnCollapsed-CompactView

All Swimlanes Collapsed
06-AllSwimlanesCollapsed

**Comment by fguillot** [comment]
LGTM. Thanks for doing that 👍

**Comment by manne65-hd** [comment]
> Thanks for doing that 👍

You are more than welcome  👍 
In fact I think that thanks are on my _(our?)_ side for providing us with this excellent piece of software as open-source 🥇

**Comment by groovybluedog** [comment]
I could kiss you for this, thank you. This increases the usability of the swimline interface tenfold. <3

**Comment by LeoShivas** [comment]
Thank you. It seems it solves partly my issue https://github.com/kanboard/kanboard/issues/4740
I'm waiting for the release :)

**Pull request merged**
