### PR TITLE
Issue #2681

### PR DESCRIPTION
**Pull request by seanxlliu**
when filter applied, now d&d drops elements where expected. Still need more work to do to get it 100% perfect.

credits to @TheCloud

### CODE REVIEW

**Comment by fguillot** [comment]
Can you add a test that prove that you are fixing the problem and not introducing any regressions?

**Comment by seanxlliu** [comment]
I can do that for sure. Do you have any guides to add tests? Or just refer to others?

**Comment by oliviermaridat** [comment]
This doc ["Running tests"](https://kanboard.net/documentation/tests) may help to understand the test architecture.

**Comment by fguillot** [comment]
Closing stale PR after 30 days.

**Pull request closed without merging**
