### PR TITLE
Avoid implicit line wrapping for input-addon-item CSS style

### PR DESCRIPTION
**Pull request by grayed**
This makes filter buttons look like fine again for me (Chromium on OpenBSD/amd64-CURRENT, 1920x1080 screen running cwm). See attached images for difference:

Before:
before

After:
after

### CODE REVIEW

**Comment by fguillot** [comment]
You should also include the app.min.css

**Comment by grayed** [comment]
@fguillot done. I've thought syncing better made separately, but, of course, your app — your rules. :)

**Comment by fguillot** [comment]
I'm trying to reproduce your issue, but I don't see the problem on my side. I tested with the same screen resolution, language set to Russian, and Chromium 79.0.3945.79 (The actual version shipped with Ubuntu). Same on Firefox 71.

What Chromium version do you have on OpenBSD?

I could merge but I don't see the difference after and before...

**Comment by grayed** [comment]
The problem disappeared after updating Calendar plugin to recently released 1.1.1. Thank you for your attention.

**Pull request closed without merging**
