### PR TITLE
MSSQL support and patch for the first login problem

### PR DESCRIPTION
**Pull request by drrobalan**
Thank you for this great software, please note that I'm not a professional PHP programmer and my knowledge of the kanboard source code is very limited. 

The proposed modifications are far from elegant and not properly tested, thus I would appreciate your help. I hope that this is an appropriate way of exposing this code to the contributors, please bare in mind that I created my github account a few hours ago just for this project.

- Only very basic testing using MSSQL (express) 2017 running on Ubuntu, it should work with 2012 onwards but not tested
- Please chose the right DB_DRIVER in the config.ini and ensure that an empty database is created as the SQL script will not drop any existing tables
- I was trying not to break any of the existing code but I have not tested it on the already supported databases
- After kanboard creates the database I was unable to log in, I made a small modification to the AuthenticationMiddleware.php to address this issue

### CODE REVIEW

**Comment by fguillot** [comment]
What is the point of adding MSSQL support? this is not a free and open source software.

**Comment by mauricio-sonegatti** [comment]
I think the point is that some shops (like mine) already use MSSQL configured as default, with no MySQL or any other open source alternatives available. 
Now I have to use sqlite with no database specific backup protocol, and pray to the database god.
For me, using my company MSSQL would be the best alternative, with all the backup protocols and greater IO.

**Comment by Dracer5** [comment]
I'm totally agree with @drrobalan . We also might use only MS SQL Server, because of IT Policies in our company. We have no Database Administrators for MySQL or SQLite, only for Oracle and SQL Server.

**Comment by lastlink** [comment]
@drrobalan @fguillot Any updates on this? Will some of this be a pull request for the picoDb vendor?  https://github.com/fguillot/picoDb

**Comment by lastlink** [comment]
@fguillot "What is the point of adding MSSQL support? this is not a free and open source software."
mssql now works on linux & you can run a docker container to quickly launch a db server. https://hub.docker.com/r/microsoft/mssql-server-linux/. You can use `docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux:2017-CU6` To launch one quickly w/ default username: sa. Then https://docs.microsoft.com/en-us/sql/sql-operations-studio/download?view=sql-server-2017 to create a db for kanboard.

**Comment by fguillot** [comment]
Closing stale pull-request.

@lastlink The point is not being able to run MSSQL locally. I'm aware that Microsoft have a Docker image. This is about maintaining and supporting this feature on the long term. Throwing a patch might be a first step. But since the comments haven't been addressed after a couple of months that means no body is really committed to maintain this.

**Pull request closed without merging**
