### PR TITLE
Task pos model fire all events

### PR DESCRIPTION
**Pull request by manne65-hd**
Do you follow the guidelines?

- [x] I have tested my changes
- [x] There is no breaking change
- [x] There is no regression
- [x] I follow existing [coding style](https://docs.kanboard.org/en/latest/developer_guide/coding_standards.html)

### Fire ALL events, when moving tasks between columns AND swimlanes _(configurable via config.php)_
There have been 3 reports in the past, about the problem that the automatic action _"Assign a color when the task is moved to a specific column"_ will only work, if the task is moved within the same swimlane.

- https://github.com/kanboard/kanboard/issues/1365
- https://github.com/kanboard/kanboard/issues/4163
- https://github.com/kanboard/kanboard/issues/4581

This PullRequest could fix these issues

#### Why is this NOT a breaking change ?
By default everything will work as before, but Administrators now have the ability to configure which EVENTS will be triggered, when tasks are being moved between swimlanes AND columns at the same time.

#### How does it work?
By setting the new parameter TRIGGER_TASK_MOVE_EVENTS in **config.php** you can control the new behavior:
- '' _(default)_
  - ONLY the MoveSwimlane-Event will be triggered _(old behaviour)_
- 'Column' 
  - ONLY the MoveColumn-Event will be triggered
- 'SwimLane+Column'
  - the MoveSwimlane-Event AND the MoveColumn-Event will be triggered
  - BEWARE >> This will also trigger 2 seperate Mail/Web-Notifications for users that subscribe to that project
- 'All'
  - the MoveSwimlane-Event, MoveColumn-Event AND the MovePosition-Event will be triggered
  - BEWARE >> This will also trigger 3 seperate Mail/Web-Notifications for users that subscribe to that project

#### Testing ?
I did quite some (manual) testing on my local machine, but if this requires adding unit-tests ... I might need help, because this is still beyond my knowledge 

Hope you like it

### CODE REVIEW

**Comment by manne65-hd** [comment]
Just a humble **bump** ...
Do you have any thoughts on this one?

The reason why I added so "many" options, is the fact that depending on which of the new options an ADMIN chooses this involves triggering more mails. So it's up to the one running a kanboard-instance to decide, what's more important to them.

 Sum up all possible change-event-notifications in a single mail ??
-----------------------------------------------------------
I'd be willing to investigate the possibility to change the mail-notifications in order to "collect" all possible 3 changes and notify them in a single mail. 
But as my understanding of kanboard's code is still at a beginner-level, I have no idea how complicated that would be and also if you would even be willing to accept such (breaking) changes.

**Comment by manne65-hd** [comment]
@fguillot 
Just another humble bump on this one ...
Could you please give me some feedback on this pull-request?

Looking forward to your answer,
Manfred

**Comment by fguillot** [comment]
I'm not really fan of `TRIGGER_TASK_MOVE_EVENTS`. Average users will keep the default value and that might introduce confusion for those using a different value. Triggering multiple notifications might create too much noise.

I would rather use a different approach. Perhaps, introducing a new event for tasks moved to a different swimlane and a different column, assuming the intend is to fix the automatic action mentioned above. I haven't touched this code in years, so I might be wrong.

**Comment by manne65-hd** [comment]
> I'm not really fan of `TRIGGER_TASK_MOVE_EVENTS`. Average users will keep the default value and that might introduce confusion for those using a different value. Triggering multiple notifications might create too much noise.

I understand that concern

> I would rather use a different approach. Perhaps, introducing a new event for tasks moved to a different swimlane and a different column, assuming the intend is to fix the automatic action mentioned above. I haven't touched this code in years, so I might be wrong.

Am i right in assuming, that this would require to create twice the amount of automatic actions?
 - Action to execute when EVENT_MOVE_COLUMN or EVENT_MOVE_SWIMLANE was triggered _(as in current version of Kanmboard)_
   - "Same" Action to execute when new EVENT_MOVE_COLUMN_SWIMLANE was triggered ?

**Comment by manne65-hd** [comment]
> I would rather use a different approach. Perhaps, introducing a new event for tasks moved to a different swimlane and a different column, assuming the intend is to fix the automatic action mentioned above. I haven't touched this code in years, so I might be wrong.

OK ... I gave this a try and introduced a new EVENT_MOVE_COL_AND_SWL.
From what I have tested locally it looks to me like to works ... but I will have to give up on trying to write a unit-test for this, as this is simply lightyears out of the scope of my (current) skill-set ;-/

Am willing to learn though, but it looks like there are many changes required to be able to run successful unit-tests on this new event.

Please advice how to go on from here.

Thank you,
Manfred

**Comment by fguillot** [comment]
Closing stale pull-request

**Pull request closed without merging**
