### PR TITLE
Feature #85 : Multiple users in one task

### PR DESCRIPTION
**Pull request by flowernert**
Implementation of Feature request #85 
Impact : 
- new table table_has_users created in the db to manage n-to-n relationship
- model class TaskHasAssignees created to map the new table
- unit tests class created for the new model class
- service provider updated with the new model class
- controllers updated 
- templates updated
- formatters updated

Unit tests pass, I performed manual interface testing of several scenarios it works fine. If guidance is provided I can also create the integration and E2E tests.

It was the most requested new feature, so I hope the feature will be useful to users ! :smile:

### CODE REVIEW

**Comment by kent1D** [comment]
Would be nice to implement asap. Very helpfull feature

**Comment by krustymars** [comment]
@kent1D if you want to use it before it's merged to the master, you can clone branche **feature85** from my fork https://github.com/krustymars/kanboard, the changes are already there.

**Comment by kent1D** [comment]
I had a look and tried it these last days and it seems to work normally. Unfortunately i can't use it in production because we would like to stay in a stable channel.

**Comment by nougel** [comment]
Nice and important feature ! Thanks ! It seems notifications about changes are not send to the assignees but only to the owner of the task, is this correct ?

**Comment by krustymars** [comment]
Thanks @nougel :) and thanks for the feedback

Indeed, for the moment the notifications mechanism hasn't been updated in order to send notifications to assignees as they have been assigned. I already had a look at the code for it, it will come into a next update.

For the time being I prefer to priorize implementation related to the feedback of @tpimont in this thread https://github.com/kanboard/kanboard/issues/85#issuecomment-327809032, as it's related to the very core functionality.

**Comment by fguillot** [comment]
Thank you for this PR. It will require some time before that gets reviewed.

**Comment by amitparmar01** [comment]
Any update on when this will be merged with the master?

**Comment by yannicka** [comment]
Just a question: why `UNIQUE(user_id, task_id)` and not a concatened primary key ?

(Very) Small review:

- `$userModel = new userModel($this->container);`. Uppercase is missing on "u" (3 times, [1](https://github.com/kanboard/kanboard/pull/3431/files#diff-2d5c786008e672dc63f34b56d6079f4aR17), [2](https://github.com/kanboard/kanboard/pull/3431/files#diff-2d5c786008e672dc63f34b56d6079f4aR61), [3](https://github.com/kanboard/kanboard/pull/3431/files#diff-2d5c786008e672dc63f34b56d6079f4aR113)).
- `public function withAssignees (array $assignees)`. There is an extra space after the function name ([here](https://github.com/kanboard/kanboard/pull/3431/files#diff-72baf63392e45aef10813b257e7f52b5R80)).
- Trailing spaces ([here](https://github.com/kanboard/kanboard/pull/3431/files#diff-2854f9020ccae6d51dad637f826a4ef2R81)).

Otherwise, good pull request, thanks.

**Comment by timnis** [comment]
Will this work with version 1.2.0?

**Comment by krustymars** [comment]
I realized the merge have been tried and failed because since I developed the feature some others PR have been integrated leading to the database scheme ID to change and conflicting with my DB schema update (see https://github.com/kanboard/kanboard/issues/85#issuecomment-366680970)

I'll update soon the db schema files to comply with this.

**Comment by fguillot** [comment]
Actually, I'm not sure how to merge this PR because this is a big change on Kanboard internals.

As of now, the assignee was stored into the column `owner_id` of tasks and all features are based on that (automatic actions, stats, plugins, etc). Some kind of migration might be needed to avoid existing Kanboard installation to be in a inconsistent state.

**Comment by krustymars** [comment]
Thanks for you feedback @fguillot , would you suggest a specific way of implementing the migration ? Is there an example of such a migration in the code base ?

**Comment by fguillot** [comment]
No change as big as this one occurs in the past. Database migrations could be used to move old assignees to the new table. But, all existing code as to be changed as well to use the new system. This is like rewriting a large chunk of the app. The risk of introducing regressions is pretty high.

**Comment by felixdivo** [comment]
But many people seem to want this feature

**Comment by GreenItSolutions** [comment]
how can we help you, fguillot ?

**Comment by lastlink** [comment]
Could this not be done as additional assignees and be a separate field from owner? This way it would not conflict with having to move users over.

**Comment by fguillot** [comment]
Closing stale pull-request.

Unfortunately, this PR cannot merged as-is without a migration from a single assignee to a multiple assignees mechanism. Everything that depends on assignees have to be updated as well to avoid breaking changes. It's a major overhaul.

If anyone wants to improve and update this branch. Don't hesitate to open a new pull-request.

**Pull request closed without merging**
