### PR TITLE
Fix word and add style cancel button

### PR DESCRIPTION
**Pull request by lfandrade**
Fix word and add style cancel button

### CODE REVIEW

**Review by fguillot — COMMENTED** [review]
You need to include your modifications in the non minified CSS file.

See https://docs.kanboard.org/en/latest/developer_guide/assets.html

**Comment by lfandrade** [comment]
> You need to include your modifications in the non minified CSS file.
> 
> See https://docs.kanboard.org/en/latest/developer_guide/assets.html

Hi, it's done ! Thank you for your reply.

**Comment by lfandrade** [comment]
Hi, ready for merge

**Comment by fguillot** [comment]
Your stylesheet doesn't really look consistent with the rest of the application. I consider that to be a breaking change.

image

It's probably better to use the custom stylesheet in that case.

Your pull-request contains 2 unrelated changes: a translation update and stylesheet change.

**Pull request closed without merging**
