### PR TITLE
new event subtask.create_update (useable in actions)

### PR DESCRIPTION
**Pull request by BlueTeck**
- add a new event `subtask.create_update` (like task.create_update)
- make event `subtask.create_update` useable in actions

### CODE REVIEW

**Comment by fguillot** [comment]
This PR has conflicts with the previous PR just merged.

**Comment by BlueTeck** [comment]
@fguillot should be mergeable now

**Comment by fguillot** [comment]
Sorry, I merged another PR. New conflicts to solve :)

**Comment by BlueTeck** [comment]
@fguillot should be mergeable once again 😅

**Pull request merged**
