### PR TITLE
Feature request #3026: Added plugin hook 'aftersave' after creating Task

### PR DESCRIPTION
**Pull request by RAZORzdenko**
This plugin hook returns ID of currently created task

### CODE REVIEW

**Comment by fguillot** [comment]
If you add a new hook, can you update the docs as well?

**Comment by RAZORzdenko** [comment]
Just updated it. Hopefully it's in line with contributing guidelines. Thank you for patience.

**Comment by kent1D** [comment]
It’s after creating ? Or after each save of tasls? For the documentation?

**Comment by kent1D** [comment]
It would be nice to have one after 1st creation and a different one after each save. Maybe with just a different parameter?

**Comment by RAZORzdenko** [comment]
This hook is only available after creating task. If you need to get task or something else after updating a task, you can look at TaskModificationModel.php and add your hook there.

https://github.com/kanboard/kanboard/blob/daf39ee16aa15572b92f96bd7cc3705305a50b9d/app/Model/TaskModificationModel.php

**Pull request merged**
