### PR TITLE
Allow task limits to be applied per-swimlane

### PR DESCRIPTION
**Pull request by andrenth**
This PR adds a configuration toggle to projects that makes task limits local to each swimline. I believe this was how Kanboard used to work and it has been requested before (e.g. #3677).

### CODE REVIEW

**Comment by BlueTeck** [comment]
Please take a look at the failing unit tests.

https://travis-ci.org/kanboard/kanboard/builds/644582377?utm_source=github_status&utm_medium=notification

**Comment by andrenth** [comment]
Hm I ran the tests locally and only got an unrelated error related to LDAP. I’ll have a look.

**Comment by andrenth** [comment]
It seems I have committed some commented code by mistake. I’ll fix it once I get home.

**Comment by andrenth** [comment]
WIth the two latest pushes, unit tests pass for sqlite and postgres. MySQL tests are running but taking a long time.

**Comment by andrenth** [comment]
So, the MySQL test failed, but I also get the same failure on master; it seem unrelated:
```
There was 1 failure:

1) TaskLinkModelTest::testGeyById
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'is a child of'
+'is a parent of'
```

**Pull request merged**
