### PR TITLE
Remove most of the border-radius

### PR DESCRIPTION
**Pull request by yannicka**
This remove most of the border-radius. I know it will be controversial, but I try anyway. I am open to discussion.

Example:
capture d ecran - 2017-10-21 a 21 03 14

### CODE REVIEW

**Comment by fguillot** [comment]
What is the problem with border-radius?

**Comment by yannicka** [comment]
There's no real problem, I just find them superfluous, I think they make the interface less beautiful.

**Comment by fguillot** [comment]
Perhaps, using a custom CSS stylesheet that remove the border-radius will avoid a controversial discussion?

**Comment by yannicka** [comment]
Yes, you are right. I'll do that.

**Pull request closed without merging**
