### PR TITLE
Feature multiboard

### PR DESCRIPTION
**Pull request by stinnux**
These PR allows having multiple Boards (for different projects) on one page. Basically all it does is forward the project id/board id to the relevant functions.

This is necessary for the Plugin https://github.com/stinnux/kanboard-bigboard. 

This replaces PR #2474

### CODE REVIEW

**Comment by fguillot** [comment]
I found a regression, the keyboard shortcuts don't seems to work anymore (collapse tasks).

**Comment by stinnux** [comment]
Where are the keyboard shortcuts defined? Can't find it.

**Comment by aljawaid** [comment]
This would be a very good feature

**Comment by orware** [comment]
I agree this would be a great feature (from the rough description above I think it's similar to an idea I was wanting to have back after we started using Kanboard earlier this year).

**Comment by ArmReu** [comment]
Any update on this feature? We'd absolutely would love to use it when release!

**Pull request closed without merging**
