### PR TITLE
remove 'project_id' from any redirect.

### PR DESCRIPTION
**Pull request by Chaosmeister**
Do you follow the guidelines?

- [x] I have tested my changes

I'll run these changes for the next weeks on our instance

- [x] There is no breaking change
- [x] There is no regression

I haven't found anything broken yet

- [x] I follow existing [coding style](https://docs.kanboard.org/en/latest/developer_guide/coding_standards.html)

This will solve #3989

### CODE REVIEW

**Comment by Jieiku** [comment]
Awesome! So Awesome! Thank you for this!

**Review by fguillot — CHANGES_REQUESTED** [review]
- [RouteProvider.php](https://github.com/kanboard/kanboard/blob/master/app/ServiceProvider/RouteProvider.php) needs to be updated accordingly
- There are some conflicts detected because other pull-requests have been merged

**Comment by Chaosmeister** [comment]
I rebased and resolved the conflicts  
I also removed the project_id from all task routes

**Comment by fguillot** [comment]
I found a couple of regressions. These actions are not working anymore:

- Task menu -> Add comment
- Task menu -> Send by email
- Task view > Comments section -> click on "Send by email"

**Comment by Chaosmeister** [comment]
Thanks for the findings

I fixed and tested the functionality locally.

**Review by fguillot — CHANGES_REQUESTED** [review]
I found another regression. Converting a subtask to a task is broken.
image

image

**Comment by Chaosmeister** [comment]
fixed  
I also removed a few more occasions, where the project_id was still transmitted

**Pull request merged**
