### PR TITLE
Add subtask events to ProjectModificationDateSubscriber

### PR DESCRIPTION
**Pull request by liedekef**
This allows also subtask updates to be reflected on the dashboard (the % info) when a subtask is completed.

### CODE REVIEW

**Comment by fguillot** [comment]
I don't see the percentage updated when changing the status of subtasks. How can I test this exactly?

**Comment by liedekef** [comment]
Well, indeed nu setting the subtask status to completed and then wait for the next Ajax board refresh. I'm using this in production since last week and it works fine.

**Comment by fguillot** [comment]
The Ajax request contains only the element `<div class="task-list-subtasks">`. This is why I don't see the percentage updated.

image

Are you using this in addition to some plugin?

**Comment by liedekef** [comment]
I just tried this on a virgin setup and it works ok. But according to your screenshot you're testing this in the controller=DashboardController&action=show view (the "main" dashboard view), while I tested this in the per-project Board view (e.g. controller=BoardViewController&action=show&project_id=1 ).
It seems the main dashboard doesn't have a planned ajax call that refreshes every X seconds, so I consider that normal. This change just adds to the per-project Board ajax calls.

**Comment by liedekef** [comment]
Hi, would it be possible to merge this?

**Comment by fguillot** [comment]
I can see it now.

**Pull request merged**
