### PR TITLE
Fix for #3466 - Uploading documents by drag and drop

### LINKED ISSUE #3466: Add/remove files to/from queue when uploading documents
**Please, do not create duplicate issues**

### Actual behaviour

When we use the dropzone to upload files, it's impossible to add more files or delete files in queue

### Expected behaviour

Add the possibility to add files by dragging files again, to delete one or more files with a button from the queue

### Configuration

Copy and paste the configuration section from the Kanboard settings page or supply values for these fields:

- Kanboard version: 1.0.45
- Database type and version: Mysql
- PHP version: 5.6.30
- OS: Debian
- Browser: All

### PR DESCRIPTION
**Pull request by kent1D**
Fix #3466

Add the possibility to add new files to the upload queue after first drag and drop

Add the possibility to remove files from queue also

### CODE REVIEW

**Comment by kent1D** [comment]
Here it is...

I am juste wondering if I need to push also the minification made from gulp or not (app.min.css)

**Comment by fguillot** [comment]
If I click on the delete button, I got a Javascript error on Chrome?

image

**Comment by kent1D** [comment]
Strange I don't have it in Chrome 61.0.3163.100

Neither in Firefox 55.0.3

**Comment by fguillot** [comment]
I merged and fixed your PR.

**Comment by kent1D** [comment]
Oh thanks

I was a bit slow :( sorry

**Pull request closed without merging**
